"""Breed metadata returned with predictions."""

BREED_INFO = {
    "angus": {
        "type": "Beef Cattle",
        "milk_yield": "Not applicable - Primarily beef breed",
        "region": "Scotland (origin), Worldwide",
        "characteristics": "Black or red, polled, excellent beef quality.",
        "lifespan": "15-20 years",
        "diet": "Grass, hay, and grain",
    },
    "brahman": {
        "type": "Beef Cattle",
        "milk_yield": "Not applicable - Beef breed",
        "region": "India (origin), tropical regions worldwide",
        "characteristics": "Large hump, drooping ears, heat tolerant.",
        "lifespan": "18-20 years",
        "diet": "Grass, hay, and roughage",
    },
    "hereford": {
        "type": "Beef Cattle",
        "milk_yield": "Not applicable - Beef breed",
        "region": "England (origin), Worldwide",
        "characteristics": "Red body with white face, docile, hardy.",
        "lifespan": "15-20 years",
        "diet": "Grass and hay",
    },
    "holstein": {
        "type": "Dairy Cattle",
        "milk_yield": "7000–9000 liters/year",
        "region": "Netherlands (origin), Worldwide",
        "characteristics": "Black and white spotted, high milk volume.",
        "lifespan": "15-20 years",
        "diet": "Hay, silage, grain concentrates",
    },
    "jersey": {
        "type": "Dairy Cattle",
        "milk_yield": "5000–7000 liters/year",
        "region": "Jersey Island (origin), Worldwide",
        "characteristics": "Light brown, small size, high butterfat milk.",
        "lifespan": "15-20 years",
        "diet": "Grass, hay, and grain",
    },
    "sahiwal": {
        "type": "Dairy Cattle",
        "milk_yield": "2500-3500 liters/year",
        "region": "India and Pakistan (Punjab)",
        "characteristics": "Reddish-brown, heat and tick resistant.",
        "lifespan": "15-20 years",
        "diet": "Grasses, crop residues, concentrate",
    },
    "simmental": {
        "type": "Dual-Purpose Cattle",
        "milk_yield": "4000–6000 liters/year",
        "region": "Switzerland (origin), Worldwide",
        "characteristics": "Red and white spotted, large frame, dual-purpose.",
        "lifespan": "15-20 years",
        "diet": "Grass, hay, and grain",
    },
    "gir": {
        "type": "Dairy Cattle",
        "milk_yield": "3000–4500 liters/year",
        "region": "Gujarat, India",
        "characteristics": "Curved horns, prominent forehead, reddish coat.",
        "lifespan": "15-18 years",
        "diet": "Green fodder, hay, concentrate",
    },
    "himachali_pahari": {
        "type": "Dual-Purpose Cattle",
        "milk_yield": "1500–2500 liters/year",
        "region": "Himachal Pradesh and Uttarakhand, India",
        "characteristics": "Compact hill breed for mountainous terrain.",
        "lifespan": "14-18 years",
        "diet": "Mountain grasses and hay",
    },
    "nari": {
        "type": "Indigenous Cattle",
        "milk_yield": "1200–2200 liters/year",
        "region": "Western India (Rajasthan, Gujarat)",
        "characteristics": "Hardy indigenous breed for arid regions.",
        "lifespan": "14-16 years",
        "diet": "Dry fodder and crop residues",
    },
    "tharparkar": {
        "type": "Dual-Purpose Cattle",
        "milk_yield": "1800–3000 liters/year",
        "region": "Thar desert (Rajasthan, India)",
        "characteristics": "White/gray coat, lyre-shaped horns, arid adapted.",
        "lifespan": "15-18 years",
        "diet": "Desert grasses and dry fodder",
    },
    "water_buffalo": {
        "type": "Dairy/Work Bovine",
        "milk_yield": "1500–3000 liters/year",
        "region": "Asia (India, Pakistan, Southeast Asia)",
        "characteristics": "Large, gray to black, curved horns.",
        "lifespan": "18-25 years",
        "diet": "Grasses, hay, agricultural byproducts",
    },
    "not_cattle": {
        "type": "Not applicable",
        "milk_yield": "Not applicable",
        "region": "Not applicable",
        "characteristics": "Non-cattle image — breed prediction blocked.",
        "lifespan": "Not applicable",
        "diet": "Not applicable",
    },
}
